### ISSUE TITLE
[BUG/ISSUE] Nether Gauntlet damage increasing from upstream

### ISSUE THREAD

**Issue by SettingDust** [CERBON-MODS/Bosses-of-Mass-Destruction-FORGE#10]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of Bosses of Mass Destruction Mod**
- [x] **I have checked the [FAQ](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/FAQ.md) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/CODE_OF_CONDUCT.md)**

## Describe the bug
https://github.com/barribob/bosses-of-mass-destruction/issues/125#issuecomment-2395336018

Haven't tested on 1.21/1.20.1. Only tested in DawnCraft that is 1.18.2

**Comment by CerbonXD** [comment]
It's now fixed in version 1.3.0 for 1.21+. I won't fix it for older versions.

**Comment by SettingDust** [comment]
well. For 1.18.2. Fixed with https://legacy.curseforge.com/minecraft/mc-mods/mod-compat-fixes
