### ISSUE TITLE
[BUG/ISSUE] Boss bars appear from too far away.

### ISSUE THREAD

**Issue by MokahTGS** [CERBON-MODS/Bosses-of-Mass-Destruction-FORGE#4]
Please either add a way in the configs to change the render distance or greatly reduce the distance at which these are visible.  You can see a Voidblossom boss bar from hundreds of blocks away.

**Comment by CerbonXD** [comment]
Wich version are you playing?

**Comment by MokahTGS** [comment]
I assume it's happening on all versions but specifically 1.20.1
