### ISSUE TITLE
[BUG/ISSUE] Crash on world load 1.20.1

### ISSUE THREAD

**Issue by Gamerbolts** [CERBON-MODS/Bosses-of-Mass-Destruction-FORGE#6]
## Before submitting the issue

- [ x ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ x ] **I have checked that I am running the latest version of Bosses of Mass Destruction [FORGE] Mod**
- [ x ] **I have checked the [FAQ](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/FAQ.md) section for solutions**
- [ x ] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/CODE_OF_CONDUCT.md)**

## Minecraft Version
1.20.1

## Describe the bug
Creating my own modpack, quite large, was trying to load a world and crashed, crash log was not real good at explaining what happened from what I can tell but I saw your mod name in the log.

## To Reproduce
Unfortunately because it is a personal pack, you wouldn't be able to take steps to reproduce as I am sure it is a conflict with another mod, which mod however I am not sure

## Expected behavior
World to load

## Latest Log
[crash-2024-01-24_17.05.46-server.txt](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/files/14045432/crash-2024-01-24_17.05.46-server.txt)

[latest.log](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/files/14045433/latest.log)

```
Please paste here the latest log (Open the folder where your Minecraft is installed and search for "logs" folder, open latest.log and paste it's content here). 
```

</details>

**Comment by CerbonXD** [comment]
Use CerbonsAPI 1.0.0 for Bosses of Mass Destruction 1.1.0.

**Comment by Gamerbolts** [comment]
That worked. I hit update all on my modpack and missed that it updated that mod. Thanks!
