### ISSUE TITLE
[FEATURE REQUEST] 1.21 version

### ISSUE THREAD

**Issue by goldrichman9Modded** [CERBON-MODS/Bosses-of-Mass-Destruction-FORGE#9]
## Before submitting the feature request

- [ yes] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [yes ] **I have checked that I am running the latest version of Bosses of Mass Destruction mod**
- [yes ] **I have checked the [FAQ](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/FAQ.md) section for solutions**
- [yes ] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/Bosses-of-Mass-Destruction-FORGE/blob/master/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
 
Nope

## Describe the solution/feature you'd like
Just a version port to 1.21

A version port to 1.21

**Comment by CerbonXD** [comment]
It's available now.
